openapi: 3.0.3
info:
    title: Informations API
    description: API to fetch the information stored in the database
    version: 1.0.0
servers:
    -   url: https://fold-backend-5e6c2cf7c25c.herokuapp.com
paths:
    /api/information:
        get:
            tags:
                - information
            description: Returns the last information of the site from de database
            summary: Returns the last information of the site from de database
            operationId: informations
            parameters:
                -   $ref: "./wgn.yml/#/components/parameters/access_token"
            responses:
                200:
                    description: OK
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/InformationDto'
                401:
                    description: Access token not valid
            deprecated: false

components:
    schemas:
        InformationDto:
            title: InformationDto
            type: object
            properties:
                text:
                    type: string
                    description: The text of the information
                    example: La clan war commence
                link:
                    $ref: '#/components/schemas/InformationLinkDto'
            required:
                - text
                - link
        InformationLinkDto:
            title: InformationLinkDto
            description: The link of the information
            type: object
            properties:
                text:
                    type: string
                    description: The text of the link
                    example: Visualisation LU clan war
                    nullable: true
                url:
                    type: string
                    description: The url of the link
                    example: path.clanWar
                    nullable: true
            required:
                - text
                - url
